#!/usr/bin/env python3
"""Generate pr2000_tables.h from the PR2000 mode tables in pr2000/.

The tables are the ones the unit's stock kernel (build #328) writes for each AHD mode,
decoded from its image: {reg, val} rows, reg 0xff selecting the register page.

Usage: pr2000-tables.py > pr2000_tables.h
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PAIRS_PER_LINE = 4

# C name, table file: the modes the driver offers
MODES = [
    ("ahd_720p25", "ahd-720p25"),
    ("ahd_720p30", "ahd-720p30"),
    ("ahd_1080p25", "ahd-1080p25"),
    ("ahd_1080p30", "ahd-1080p30"),
]


def rows(name):
    """(reg, val) pairs of one table, comment lines skipped."""
    with open(os.path.join(HERE, "pr2000", name + ".tsv")) as f:
        return [tuple(int(x, 16) for x in line.split()[:2])
                for line in f if line.strip() and not line.startswith("#")]


def main():
    print("/* SPDX-License-Identifier: GPL-2.0 */")
    print("/*")
    print(" * PR2000 mode tables, read out of the stock 4.14.190 kernel (build #328) of the")
    print(" * Choiceway GT6-EAU head unit. Each is {reg, val}; reg 0xff selects the register page.")
    print(" * Generated by os/mainline/pr2000-tables.py; do not edit by hand.")
    print(" */")
    print("#ifndef PR2000_TABLES_H\n#define PR2000_TABLES_H\n")
    for cname, fname in MODES:
        table = rows(fname)
        print("static const struct pr2000_reg pr2000_%s[] = {" % cname)
        for i in range(0, len(table), PAIRS_PER_LINE):
            print("\t" + " ".join("{ 0x%02x, 0x%02x }," % r for r in table[i:i + PAIRS_PER_LINE]))
        print("};\n")
    print("#endif")


if __name__ == "__main__":
    main()
