#!/usr/bin/env python3
"""Generate xs9922b_tables.h from the XS9922B tables in xs9922b/.

The tables are the ones the unit's stock AIS camera driver (libais_xs9922b.so) writes in
xs9922b_sensor_start_stream: a pre table and a resolution table per mode, then the start of
all four channels. Rows are {reg (16 bit), val, delay}.

Usage: xs9922b-tables.py > xs9922b_tables.h
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROWS_PER_LINE = 3

# C name, table file
TABLES = [
    ("pre_1080p", "pre-1080p"),
    ("res_1080p", "res-1080p"),
    ("pre_720p", "pre-720p"),
    ("res_720p", "res-720p"),
    ("stream_all", "stream-all"),
]


def rows(name):
    """(reg, val, delay) rows of one table, comment lines skipped."""
    with open(os.path.join(HERE, "xs9922b", name + ".tsv")) as f:
        return [tuple(int(x, 0) for x in line.split()[:3])
                for line in f if line.strip() and not line.startswith("#")]


def main():
    print("/* SPDX-License-Identifier: GPL-2.0 */")
    print("/*")
    print(" * XS9922B tables from the stock AIS camera driver of the Choiceway GT6-EAU head unit.")
    print(" * Each is {reg, val, delay ms}. Generated by os/mainline/xs9922b-tables.py; do not")
    print(" * edit by hand.")
    print(" */")
    print("#ifndef XS9922B_TABLES_H\n#define XS9922B_TABLES_H\n")
    for cname, fname in TABLES:
        table = rows(fname)
        print("static const struct xs9922b_reg xs9922b_%s[] = {" % cname)
        for i in range(0, len(table), ROWS_PER_LINE):
            print("\t" + " ".join("{ 0x%04x, 0x%02x, %d }," % r for r in table[i:i + ROWS_PER_LINE]))
        print("};\n")
    print("#endif")


if __name__ == "__main__":
    main()
