#!/usr/bin/env python3
"""Plan sector writes of logical-partition images into `super` from an `lpdump` listing.

    lpdump super.img  ──parse──►  {system_b: [(sector, nsectors), …]}  ──►  `edl ws` commands

Virtual A/B keeps logical partitions for the running slot only, so a restore over EDL writes
each backup image into the extents `super`'s metadata already names, without rebuilding the
metadata. An image larger than its extents is refused.

Two sector sizes meet here and the plan converts between them:

    lpdump extents      512-byte sectors, relative to the start of `super`   (liblp fixed)
    edl ws <sector>     device sectors, 4096 on UFS (`--memory=ufs`), absolute

Usage: edl-extents.py --lpdump DUMP.txt --super-offset BYTES --images DIR --out PLAN.sh
  BYTES = `Offset` of `super` in `edl printgpt` (already in bytes). An extent that does not
  start on a device sector is refused rather than rounded.
"""
import argparse
import os
import re
import sys

LP_SECTOR = 512          # liblp always describes extents in 512-byte sectors
UFS_SECTOR = 4096        # what `edl --memory=ufs` means by a sector
IMAGES = ("system", "system_ext", "product", "vendor")


def parse(text):
    parts, name = {}, None
    for line in text.splitlines():
        m = re.match(r"\s*Name:\s*(\S+)", line)
        if m:
            name = m.group(1)
            parts.setdefault(name, [])
            continue
        m = re.match(r"\s*(\d+)\s*\.\.\s*(\d+)\s+linear\s+\S+\s+(\d+)", line)
        if m and name:
            first, last, phys = (int(x) for x in m.groups())
            parts[name].append((phys, last - first + 1))
    return parts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lpdump", required=True)
    ap.add_argument("--super-offset", type=int, required=True, help="byte offset of super (printgpt Offset)")
    ap.add_argument("--sectorsize", type=int, default=UFS_SECTOR, help="device sector size edl ws uses")
    ap.add_argument("--images", required=True)
    ap.add_argument("--slot", default="b")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    parts = parse(open(a.lpdump).read())
    lines = ["#!/bin/bash", "# generated by edl-extents.py; run on the laptop with the unit in EDL", "set -euo pipefail",
             'EDL=${EDL:-"../venv/bin/python edl.py --memory=ufs --loader=../prog_firehose_qcm6125.bin"}']
    for p in IMAGES:
        img = os.path.join(a.images, f"{p}.img")
        name = f"{p}_{a.slot}"
        if not os.path.exists(img) or name not in parts:
            print(f"skip {name}: no image or no extents", file=sys.stderr)
            continue
        size = os.path.getsize(img)
        extents = parts[name]
        capacity = sum(n for _, n in extents) * LP_SECTOR
        if size > capacity:
            sys.exit(f"{name}: image {size} bytes > extents {capacity} bytes; refuse")
        offset = 0
        for i, (phys, nsect) in enumerate(extents):
            chunk = min(nsect * LP_SECTOR, size - offset)
            if chunk <= 0:
                break

            # Absolute device sector of this extent: super's byte offset plus the 512-byte
            # extent offset, divided by the device sector size. Must divide exactly.
            start_bytes = a.super_offset + phys * LP_SECTOR
            if start_bytes % a.sectorsize:
                sys.exit(f"{name} extent {i}: byte {start_bytes} is not on a {a.sectorsize}-byte sector; refuse")
            start = start_bytes // a.sectorsize

            piece = f"{p}.part{i}.img"
            lines.append(f"dd if={img} of={piece} bs=4M iflag=skip_bytes,count_bytes skip={offset} count={chunk} status=none")
            lines.append(f"$EDL ws {start} {piece}   # {name} extent {i}: {chunk} bytes")
            offset += chunk
        print(f"{name}: {size} bytes into {len(extents)} extent(s), capacity {capacity}", file=sys.stderr)
    open(a.out, "w").write("\n".join(lines) + "\n")
    print(f"plan written: {a.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
