#!/usr/bin/env python3
"""Plan sector writes of logical-partition images into `super` from an `lpdump` listing.

    lpdump super.img  ──parse──►  {system_b: [(sector, nsectors), …]}  ──►  `edl ws` commands

Virtual A/B keeps logical partitions for the running slot only, so a restore over EDL writes
each backup image into the extents `super`'s metadata already names, at 512-byte sectors,
without rebuilding the metadata. An image larger than its extents is refused.

Usage: edl-extents.py --lpdump DUMP.txt --super-sector S --images DIR --out PLAN.sh
  S = first sector of the `super` GPT partition (edl printgpt), so `ws` offsets are absolute.
"""
import argparse
import os
import re
import sys

SECTOR = 512
IMAGES = ("system", "system_ext", "product", "vendor")


def parse(text):
    parts, name = {}, None
    for line in text.splitlines():
        m = re.match(r"\s*Name:\s*(\S+)", line)
        if m:
            name = m.group(1)
            parts.setdefault(name, [])
            continue
        m = re.match(r"\s*(\d+)\s*\.\.\s*(\d+)\s+linear\s+\S+\s+(\d+)", line)
        if m and name:
            first, last, phys = (int(x) for x in m.groups())
            parts[name].append((phys, last - first + 1))
    return parts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lpdump", required=True)
    ap.add_argument("--super-sector", type=int, required=True)
    ap.add_argument("--images", required=True)
    ap.add_argument("--slot", default="b")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    parts = parse(open(a.lpdump).read())
    lines = ["#!/bin/bash", "# generated by edl-extents.py; run on the laptop with the unit in EDL", "set -euo pipefail",
             'EDL=${EDL:-"../venv/bin/python edl.py --memory=ufs --loader=../prog_firehose_qcm6125.bin"}']
    for p in IMAGES:
        img = os.path.join(a.images, f"{p}.img")
        name = f"{p}_{a.slot}"
        if not os.path.exists(img) or name not in parts:
            print(f"skip {name}: no image or no extents", file=sys.stderr)
            continue
        size = os.path.getsize(img)
        extents = parts[name]
        capacity = sum(n for _, n in extents) * SECTOR
        if size > capacity:
            sys.exit(f"{name}: image {size} bytes > extents {capacity} bytes; refuse")
        offset = 0
        for i, (phys, nsect) in enumerate(extents):
            chunk = min(nsect * SECTOR, size - offset)
            if chunk <= 0:
                break
            piece = f"{p}.part{i}.img"
            lines.append(f"dd if={img} of={piece} bs=4M iflag=skip_bytes,count_bytes skip={offset} count={chunk} status=none")
            lines.append(f"$EDL ws {a.super_sector + phys} {piece}   # {name} extent {i}: {chunk} bytes")
            offset += chunk
        print(f"{name}: {size} bytes into {len(extents)} extent(s), capacity {capacity}", file=sys.stderr)
    open(a.out, "w").write("\n".join(lines) + "\n")
    print(f"plan written: {a.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
